### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by wenq1** [tangyiyang/seal2d#32]
Is android going to be supported soon?

Btw the iOS build is broken in the HEAD commit, due to missing array_map.c and its corresponding unit_test.

**Comment by tangyiyang** [comment]
Android version is on it's way. I found someone who is experienced in Android and cocos2d-x, also he said he would help me build the Android version very soon.

The iOS version is often late for the mac version for serveral days.
What's more, it looks like the XCode project is need to make the file changes easier, I would fix this very soon.

:)
