### ISSUE TITLE
basic design doc

### ISSUE THREAD

**Issue by wenq1** [tangyiyang/seal2d#35]
Do you have a brief description of the design (game loop, input handling, script binding points)? I currently do not have the latest iOS sdk installed. If you do I might be able to chip in and do some work on Android. Of course there's no need to be formal at this point

**Comment by tangyiyang** [comment]
Sadly, there are not any design document yet, :(

But there are some basic module description of the engine on the wiki page:
https://github.com/tangyiyang/seal2d/wiki (in Chinese),
I believe the most complicated part is the boot process of the game,
actually it is more or less like the ejoy2D.
The iOS version is ready to use, simulator is also supported.

And the game loop is really simple. It's just a simple scene-graph
(node-child-parent system) , with seal_update(), seal_draw() to be called
each frame.

You can check the GameViewController.m to catch up a basic idea of how the
engine runs.

    seal_load_game_config();

    seal_init_graphics();

    seal_start_game();

    seal_update();

    seal_draw();

    seal_destroy();

these function should be concerned if you were to port to Android. :)


2016-10-15 12:01 GMT+08:00 wenq1 <notifications@github.com>:

**Comment by wenq1** [comment]
ok actually the boot part can be kept simple, and I could do an android port as soon as I have a bit of time. However the overall design decision has to be known so that the goals are clear at the beginning and efforts will not be wasted.

**Comment by wenq1** [comment]
Well as far as I can see the docs from the wiki link are good enough. I close the issue now.

**Comment by tangyiyang** [comment]
Wiki and design principal have been updated. :)

2016-10-15 23:32 GMT+08:00 wenq1 <notifications@github.com>:
